# Use PHP 7.2 with Apache as the base image
FROM php:8.0-apache

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    gnupg \
    && apt-get clean

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Create a project-specific directory
RUN mkdir -p /var/www/html/php80

# Set the working directory
WORKDIR /var/www/html

# Enable Apache mod_rewrite for pretty URLs
RUN a2enmod rewrite

# Copy entrypoint script into the container
COPY ./entrypoint.sh /entrypoint.sh

# Make sure the entrypoint script is executable
RUN chmod +x /entrypoint.sh

# Expose port 80
EXPOSE 80

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]